spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_user?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: (schedule)QUbczcjxjchQR+rVnsm/uzmeOzfHwdgf5jrnQj9nF8g=
    password: (schedule)b2A576pm1072ITHsAijGsw8kxkNSth/2tvx10JQEmkSwPocVOLNOuxDs90q5CBAO
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: (schedule)ShuBdwFN1ENGFxStNDEolJqj7+uEhUqx1YrNAbreK8U=
