server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
  servlet:
    context-path: /Account
  port: 9093
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    cache: true
  mvc:
    static-path-pattern: classpath:/static/
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    active: datasource,local,url
  freemarker:
    prefer-file-system-access: false
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml
  type-aliases-package: org.joven.account.entity

#https://blog.csdn.net/qq_27317475/article/details/81168241
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://center-second:8762/eureka/
    #eureka client刷新本地缓存时间
    #默认30s
    registry-fetch-interval-seconds: 5
